### PR TITLE
Setup mkdocs

### PR DESCRIPTION
**Pull request by alexhq**
This PR sets up an mkdocs site for the example guides.
Generating SVGs from PUML at build time will be handled in a separate PR

### CODE REVIEW

**Comment by mtbc** [comment]
With a naive `mkdocs serve` I don't seem to have the Manufacturing SVGs generated but it's plausible I'm not reproducing the correct build environment. (My mkdocs-build-plantuml-plugin is at v1.7.4.) Just something for another reviewer to look out for.

**Comment by mtbc** [comment]
It may be appropriate to remove the `$(1)-diagrams` target in the make file.

**Comment by alexhq** [comment]
> With a naive `mkdocs serve` I don't seem to have the Manufacturing SVGs generated but it's plausible I'm not reproducing the correct build environment. (My mkdocs-build-plantuml-plugin is at v1.7.4.) Just something for another reviewer to look out for.

I've moved the diagram changes out to a separate PR, this now only adds mkdocs setup

**Comment by alexhq** [comment]
> It may be appropriate to remove the `$(1)-diagrams` target in the make file.

Thanks, I'll address this in a separate PR with the diagram changes

**Review by suchapalaver — APPROVED** [review]

**Pull request merged**
